kind: pipeline
name: default

steps:
  # Restore the cache if it exists
  - name: restore-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      restore: true

  - name: authenticate
    image: robertstettner/drone-mvn-auth
    pull: always
    settings:
      servers:
        from_secret: maven_servers
      profiles:
        - id: ssb-bip
          repositories:
            - id: ssb-bip-snapshots
              url: https://nexus.prod-bip-ci.ssb.no/repository/maven-snapshots/
              layout: default
            - id: ssb-bip-releases
              url: https://nexus.prod-bip-ci.ssb.no/repository/maven-releases/
              layout: default

  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn clean verify -U -P ssb-bip -Dmaven.repo.local=/drone/src/.m2/repository --no-transfer-progress --batch-mode --global-settings settings.xml
    environment:
      MAVEN_OPTS: -Djdk.tls.client.protocols="TLSv1.2"
    depends_on:
      - authenticate
      - restore-cache

  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn verify test -P ssb-bip,coverage -Dmaven.repo.local=/drone/src/.m2/repository --batch-mode --global-settings settings.xml
    environment:
      MAVEN_HOME: /drone/src/.m2
      M2_HOME: /drone/src/.m2
    depends_on:
      - build

  - name: publish-maven
    image: maven:3-jdk-11-slim
    commands:
      - mvn clean deploy -P ssb-bip -Dmaven.repo.local=/drone/src/.m2/repository -DskipTests=true --batch-mode --global-settings settings.xml
    environment:
      MAVEN_OPTS: -Djdk.tls.client.protocols="TLSv1.2"
    when:
      event:
        exclude: pull_request
      branch:
        - master
        - develop
    depends_on:
      - test

  - name: sonarqube
    image: maven:3-jdk-11
    commands:
      - # mvn -X -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_PROJECTKEY sonar:sonar -P ssb-bip -Dmaven.repo.local=/drone/src/.m2/repository --batch-mode --global-settings settings.xml
    environment:
      SONAR_HOST_URL: https://sonarqube.prod-bip-ci.ssb.no
      SONAR_PROJECTKEY:
        from_secret: sonar_token
    depends_on:
      - test

  # Rebuild cache if it has changed with this build
  - name: rebuild-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      rebuild: true
      mount:
        - .m2/repository
    depends_on:
      - publish-maven

  # OPTIONAL: Flush the cache of old cache items (older than 14 days)
  - name: flush-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      flush: true
      flush_age: 14
    depends_on:
      - publish-maven

  #  - name: codecov-manual
  #    image: alpine:3
  #    commands:
  #      - apk add --no-cache bash curl findutils git
  #      - curl -s https://codecov.io/bash | bash
  #    environment:
  #      CODECOV_TOKEN:
  #        from_secret: codecov_token
  #    depends_on:
  #      - test
  #
  #  - name: codecov-plugin
  #    image: plugins/codecov
  #    settings:
  #      token:
  #        from_secret: codecov_token
  #    depends_on:
  #      - test
  #
  #  - name: codacy
  #    image: maven:3-jdk-11
  #    commands:
  #      - curl -Ls -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/6.0.6/codacy-coverage-reporter-linux"
  #      - chmod +x codacy-coverage-reporter
  #      - ./codacy-coverage-reporter report -l Java -r target/site/jacoco/jacoco.xml
  #    environment:
  #      CODACY_PROJECT_TOKEN:
  #        from_secret: codacy_token
  #    depends_on:
  #      - test
  #
  #  - name: code-analysis
  #    image: aosapps/drone-sonar-plugin
  #    settings:
  #      sonar_host:
  #        from_secret: sonar_host
  #      sonar_token:
  #        from_secret: sonar_token
  #    depends_on:
  #      - build

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: bip-ci-test
    when:
      status: [ success, failure ]
    depends_on:
      - publish-maven

---
kind: secret
name: maven_servers
get:
  path: drone-maven-servers
  name: ssb-bip-maven-servers

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url

---
kind: secret
name: sonar_host
get:
  path: drone-sonarqube-configuration
  name: url

---
kind: secret
name: sonar_token
get:
  path: drone-sonarqube-configuration
  name: token

---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
---
kind: secret
name: gcs_credentials
get:
  path: drone-gcs-credentials
  name: gcs-credentials
